### ISSUE TITLE
Replace MS Explorer ?

### ISSUE THREAD

**Issue by daslicht** [WilliamDrt/DrtFMngPreview#6]
Hi,
is it possible to replace teh MS Built Explorer with this ?How about OS systemwide  file opening dialogs ?

**Comment by WilliamDrt** [comment]
You can use it as a program instead of explorer but no, system file open/save is controlled by MS not me. I do not know any alternative file manager that can do that.

**Comment by daslicht** [comment]
Thank you for the answer, so we are still doomed to wait MS finally improve the Exploder
